version: "3.3"
services:
  postgresql:
    image: postgres:13.5
    container_name: postgres
    ports:
      - "5432:5432/tcp"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=core
      - PGDATA=/var/lib/postgresql/data/pgdata